### ISSUE TITLE
Can't install this cartridge via the reflector

### ISSUE THREAD

**Issue by djmccormick** [wshearn/openshift-origin-cartridge-nodejs#3]
Results:

	The cartridge 'http://cartreflect-claytondev.rhcloud.com/reflect?github=wshearn/openshift-origin-cartridge-nodejs' will be downloaded and installed

	Application Options
	-------------------
	Domain:     foobaz
	Cartridges: http://cartreflect-claytondev.rhcloud.com/reflect?github=wshearn/openshift-origin-cartridge-nodejs
	Gear Size:  default
	Scaling:    no

	Creating application 'client' ... /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/client.rb:770:in `handle_error!': The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 54d1ac745973caac480000a3 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c4,c799' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log 2>&1\""' returned an error. rc=255 (RHC::Rest::ValidationException)

	.Last 10 kB of build output:
	d
	npm http 200 https://registry.npmjs.org/parseurl
	npm http GET https://registry.npmjs.org/etag/-/etag-1.5.1.tgz
	npm http GET https://registry.npmjs.org/fresh/-/fresh-0.2.4.tgz
	npm http GET https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz
	npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.5.tgz
	npm http 200 https://registry.npmjs.org/accepts/-/accepts-1.2.3.tgz
	npm http GET https://registry.npmjs.org/methods/-/methods-1.1.1.tgz
	npm http GET https://registry.npmjs.org/on-finished/-/on-finished-2.2.0.tgz
	npm http GET https://registry.npmjs.org/parseurl/-/parseurl-1.3.0.tgz
	npm http 200 https://registry.npmjs.org/proxy-addr
	npm http 200 https://registry.npmjs.org/content-disposition/0.5.0
	npm http 200 https://registry.npmjs.org/etag/-/etag-1.5.1.tgz
	npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.2.4.tgz
	npm http 200 https://registry.npmjs.org/depd/-/depd-1.0.0.tgz
	npm http 200 https://registry.npmjs.org/range-parser
	npm http GET https://registry.npmjs.org/character-parser/1.2.1
	npm http GET https://registry.npmjs.org/constantinople
	npm http GET https://registry.npmjs.org/coveralls
	npm http GET https://registry.npmjs.org/mkdirp
	npm http GET https://registry.npmjs.org/transformers/2.1.0
	npm http GET https://registry.npmjs.org/void-elements
	npm http GET https://registry.npmjs.org/commander
	npm http GET https://registry.npmjs.org/with
	npm http 200 https://registry.npmjs.org/debug/-/debug-2.1.1.tgz
	npm http 200 https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz
	npm http 200 https://registry.npmjs.org/methods/-/methods-1.1.1.tgz
	npm http 200 https://registry.npmjs.org/on-finished/-/on-finished-2.2.0.tgz
	npm http 200 https://registry.npmjs.org/escape-html/-/escape-html-1.0.1.tgz
	npm http 200 https://registry.npmjs.org/finalhandler/0.3.3
	npm http 200 https://registry.npmjs.org/send/0.11.1
	npm http 200 https://registry.npmjs.org/parseurl/-/parseurl-1.3.0.tgz
	npm http GET https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.6.tgz
	npm http 200 https://registry.npmjs.org/vary
	npm http 200 https://registry.npmjs.org/type-is
	npm http GET https://registry.npmjs.org/range-parser/-/range-parser-1.0.2.tgz
	npm http GET https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.0.tgz
	npm http 200 https://registry.npmjs.org/serve-static
	npm http 200 https://registry.npmjs.org/path-to-regexp/0.1.3
	npm http 200 https://registry.npmjs.org/qs/2.3.3
	npm http 200 https://registry.npmjs.org/cookie/0.1.2
	npm http 200 https://registry.npmjs.org/merge-descriptors/0.0.2
	npm http 200 https://registry.npmjs.org/utils-merge/1.0.0
	npm http GET https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.3.tgz
	npm http 200 https://registry.npmjs.org/constantinople
	npm http 200 https://registry.npmjs.org/character-parser/1.2.1
	npm http GET https://registry.npmjs.org/send/-/send-0.11.1.tgz
	npm http 200 https://registry.npmjs.org/mkdirp
	npm http GET https://registry.npmjs.org/vary/-/vary-1.0.0.tgz
	npm http 200 https://registry.npmjs.org/void-elements
	npm http 200 https://registry.npmjs.org/coveralls
	npm http GET https://registry.npmjs.org/type-is/-/type-is-1.5.6.tgz
	npm http GET https://registry.npmjs.org/serve-static/-/serve-static-1.8.1.tgz
	npm http 200 https://registry.npmjs.org/with
	npm http 200 https://registry.npmjs.org/transformers/2.1.0
	npm http 200 https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.6.tgz
	npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-1.0.2.tgz
	npm http 200 https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.0.tgz
	npm http GET https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.3.tgz
	npm http GET https://registry.npmjs.org/qs/-/qs-2.3.3.tgz
	npm http 200 https://registry.npmjs.org/commander
	npm http GET https://registry.npmjs.org/cookie/-/cookie-0.1.2.tgz
	npm http GET https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-0.0.2.tgz
	npm http 200 https://registry.npmjs.org/vary/-/vary-1.0.0.tgz
	npm http 200 https://registry.npmjs.org/type-is/-/type-is-1.5.6.tgz
	npm http GET https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz
	npm http GET https://registry.npmjs.org/constantinople/-/constantinople-3.0.1.tgz
	npm http 200 https://registry.npmjs.org/serve-static/-/serve-static-1.8.1.tgz
	npm http 200 https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.3.tgz
	npm http 200 https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.3.tgz
	npm http 200 https://registry.npmjs.org/qs/-/qs-2.3.3.tgz
	npm http GET https://registry.npmjs.org/character-parser/-/character-parser-1.2.1.tgz
	npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.1.2.tgz
	npm http 200 https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-0.0.2.tgz
	npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
	npm http 200 https://registry.npmjs.org/send/-/send-0.11.1.tgz
	npm http GET https://registry.npmjs.org/void-elements/-/void-elements-1.0.0.tgz
	npm http 200 https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz
	npm http 200 https://registry.npmjs.org/constantinople/-/constantinople-3.0.1.tgz
	npm http GET https://registry.npmjs.org/with/-/with-4.0.0.tgz
	npm http 200 https://registry.npmjs.org/character-parser/-/character-parser-1.2.1.tgz
	npm http GET https://registry.npmjs.org/transformers/-/transformers-2.1.0.tgz
	npm http GET https://registry.npmjs.org/commander/-/commander-2.6.0.tgz
	npm ERR! Error: No compatible version found: coveralls@'^2.11.2'
	npm ERR! Valid install targets:
	npm ERR! ["1.0.0","1.1.0","1.1.1","1.1.2","1.1.3","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.0.8","2.0.9","2.0.10","2.0.11","2.0.12","2.0.13","2.0.15","2.0.16","2.1.0","2.2.0","2.3.0","2.5.0","2.6.0","2.6.1","2.7.0","2.7.1","2.8.0","2.10.0","2.10.1","2.11.0","2.11.1","2.11.2"]
	npm ERR!     at installTargetsError (/var/lib/openshift/54d1ac745973caac480000a3/nodejs/versions/0.10/lib/node_modules/npm/lib/cache.js:709:10)
	npm ERR!     at /var/lib/openshift/54d1ac745973caac480000a3/nodejs/versions/0.10/lib/node_modules/npm/lib/cache.js:631:10
	npm ERR!     at saved (/var/lib/openshift/54d1ac745973caac480000a3/nodejs/versions/0.10/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
	npm ERR!     at Object.oncomplete (fs.js:107:15)
	npm ERR! If you need help, you may report this log at:
	npm ERR!     <http://github.com/isaacs/npm/issues>
	npm ERR! or email it to:
	npm ERR!     <npm-@googlegroups.com>

	npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
	npm ERR! command "/var/lib/openshift/54d1ac745973caac480000a3/nodejs//bin/node/node" "/var/lib/openshift/54d1ac745973caac480000a3/nodejs/bin/node/npm" "install" "--production"
	npm ERR! cwd /var/lib/openshift/54d1ac745973caac480000a3/app-root/runtime/repo
	npm ERR! node -v v0.10.20
	npm ERR! npm -v 1.2.24
	npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
	npm http 200 https://registry.npmjs.org/void-elements/-/void-elements-1.0.0.tgz
	npm http 200 https://registry.npmjs.org/with/-/with-4.0.0.tgz
	npm http 200 https://registry.npmjs.org/transformers/-/transformers-2.1.0.tgz
	npm http 200 https://registry.npmjs.org/commander/-/commander-2.6.0.tgz
	npm http GET https://registry.npmjs.org/crc/3.2.1
	npm http GET https://registry.npmjs.org/ee-first/1.1.0
	npm http GET https://registry.npmjs.org/mime-types
	npm http GET https://registry.npmjs.org/negotiator/0.5.0
	npm http GET https://registry.npmjs.org/forwarded
	npm http GET https://registry.npmjs.org/ipaddr.js/0.1.8
	npm http GET https://registry.npmjs.org/destroy/1.0.3
	npm http GET https://registry.npmjs.org/mime/1.2.11
	npm http GET https://registry.npmjs.org/ms/0.7.0
	npm http 200 https://registry.npmjs.org/crc/3.2.1
	npm http GET https://registry.npmjs.org/crc/-/crc-3.2.1.tgz
	npm http 200 https://registry.npmjs.org/forwarded
	npm http GET https://registry.npmjs.org/ms/0.6.2
	npm http GET https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz
	npm http 200 https://registry.npmjs.org/mime-types
	npm http GET https://registry.npmjs.org/mime-types/-/mime-types-2.0.8.tgz
	npm http 200 https://registry.npmjs.org/destroy/1.0.3
	npm http 200 https://registry.npmjs.org/ee-first/1.1.0
	npm http GET https://registry.npmjs.org/destroy/-/destroy-1.0.3.tgz
	npm http 200 https://registry.npmjs.org/mime/1.2.11
	npm http GET https://registry.npmjs.org/ee-first/-/ee-first-1.1.0.tgz
	npm http GET https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
	npm http 200 https://registry.npmjs.org/ms/0.6.2
	npm http 200 https://registry.npmjs.org/ms/0.7.0
	npm http GET https://registry.npmjs.org/ms/-/ms-0.7.0.tgz
	npm http GET https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
	npm http 200 https://registry.npmjs.org/crc/-/crc-3.2.1.tgz
	npm http 200 https://registry.npmjs.org/ipaddr.js/0.1.8
	npm http 200 https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz
	npm http GET https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-0.1.8.tgz
	npm http 200 https://registry.npmjs.org/mime-types/-/mime-types-2.0.8.tgz
	npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
	npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.0.tgz
	npm http 200 https://registry.npmjs.org/destroy/-/destroy-1.0.3.tgz
	npm http 200 https://registry.npmjs.org/negotiator/0.5.0
	npm http 200 https://registry.npmjs.org/ee-first/-/ee-first-1.1.0.tgz
	npm http 200 https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
	npm http 200 https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-0.1.8.tgz
	npm http GET https://registry.npmjs.org/negotiator/-/negotiator-0.5.0.tgz
	npm http 200 https://registry.npmjs.org/negotiator/-/negotiator-0.5.0.tgz
	npm http GET https://registry.npmjs.org/mime-db
	npm http 200 https://registry.npmjs.org/mime-db
	npm http GET https://registry.npmjs.org/mime-db/-/mime-db-1.6.0.tgz
	npm http 200 https://registry.npmjs.org/mime-db/-/mime-db-1.6.0.tgz
	npm ERR! 
	npm ERR! Additional logging details can be found in:
	npm ERR!     /var/lib/openshift/54d1ac745973caac480000a3/app-root/runtime/repo/npm-debug.log
	npm ERR! not ok code 0
	An error occurred executing 'gear postreceive' (exit code: 1)
	Error message: CLIENT_ERROR: Failed to execute: 'control build' for /var/lib/openshift/54d1ac745973caac480000a3/nodejs

	For more details about the problem, try running the command again with the '--trace' option.
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/client.rb:423:in `block in request'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/client.rb:405:in `block in attempt'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/client.rb:404:in `each'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/client.rb:404:in `attempt'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/client.rb:411:in `request'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/base.rb:30:in `rest_method'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/rest/domain.rb:68:in `add_application'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/commands/app.rb:606:in `create_app'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/commands/app.rb:155:in `block in create'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/highline_extensions.rb:190:in `call'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/highline_extensions.rb:190:in `section'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/highline_extensions.rb:204:in `paragraph'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/helpers.rb:337:in `block (2 levels) in <module:Helpers>'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/commands/app.rb:151:in `create'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/commands.rb:294:in `execute'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/commands.rb:285:in `block (3 levels) in to_commander'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:419:in `run_active_command'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/command_runner.rb:100:in `run!'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/lib/rhc/cli.rb:37:in `start'
		from /Library/Ruby/Gems/2.0.0/gems/rhc-1.34.2/bin/rhc:20:in `<top (required)>'
		from /usr/bin/rhc:23:in `load'
		from /usr/bin/rhc:23:in `<main>'

**Comment by ryanj** [comment]
I think this downloadable node cart is still working:
https://github.com/ryanj/openshift-origin-cartridge-nodejs
